- alias: homeassistant status
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant Start
      message: 'Home Assistant wurde gestartet.'

- alias: homeassistant shutdown
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant Shutdown
      message: 'Home Assistant wurde heruntergefahren'

- alias: New Device Detection
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.pushbullet
    data_template:
      title: Neues Ger채t im Netzwerk
      message: >
        Ein neues Ger채t wurde im Netzwerk registriert:
        {{trigger.event.data.host_name}}
        ({{trigger.event.data.entity_id}})

- alias: Radio
  trigger:
    platform: state
    entity_id: input_boolean.start_radio
    to: 'on'
  action:
    service: script.radio_start

- alias: Radiostop
  trigger:
    platform: state
    entity_id: input_boolean.start_radio
    to: 'off'
  action:
    service: media_player.media_stop

- alias: Wecker
  trigger:
    platform: template
    value_template: '{{ states.input_select.wake_up_time.state == states.sensor.time.state }}'
  condition:
    condition: state
    entity_id: input_boolean.alarm_toggle
    state: 'on'
  action:
    service: script.radio_start



####################################################
##           Cast Volume Sliders                   #
####################################################


- alias: Set Volume Slider K체che
  trigger:
    platform: state
    entity_id: media_player.kuche
  action:
    service: input_number.select_value
    data_template:
      entity_id: input_number.volume_kuche
      value: '{{ trigger.to_state.attributes.volume_level }}'

- alias: Set Volume from Slider K체che
  trigger:
    platform: state
    entity_id: input_number.volume_kuche
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.kuche
      volume_level: '{{ trigger.to_state.state }}'

- alias: Set Volume Slider Wohnzimmer
  trigger:
    platform: state
    entity_id: media_player.wohnzimmer
  action:
    service: input_number.select_value
    data_template:
      entity_id: input_number.volume_wohnzimmer
      value: '{{ trigger.to_state.attributes.volume_level }}'

- alias: Set Volume from Slider Wohnzimmer
  trigger:
    platform: state
    entity_id: input_number.volume_wohnzimmer
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.wohnzimmer
      volume_level: '{{ trigger.to_state.state }}'

- alias: Set Volume Slider Kinderzimmer
  trigger:
    platform: state
    entity_id: media_player.kinderzimmer
  action:
    service: input_number.select_value
    data_template:
      entity_id: input_number.volume_kinderzimmer
      value: '{{ trigger.to_state.attributes.volume_level }}'

- alias: Set Volume from Slider Kinderzimmer
  trigger:
    platform: state
    entity_id: input_number.volume_kinderzimmer
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.kinderzimmer
      volume_level: '{{ trigger.to_state.state }}'

- alias: Set Volume Slider Schlafzimmer
  trigger:
    platform: state
    entity_id: media_player.schlafzimmer
  action:
    service: input_number.select_value
    data_template:
      entity_id: input_number.volume_schlafzimmer
      value: '{{ trigger.to_state.attributes.volume_level }}'

- alias: Set Volume from Slider Schlafzimmer
  trigger:
    platform: state
    entity_id: input_number.volume_schlafzimmer
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.schlafzimmer
      volume_level: '{{ trigger.to_state.state }}'
